env:
  browser: true
  commonjs: true
  es6: true
  node: true
parser: 'babel-eslint'
extends:
  - 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
